updates:
  - commit-message:
      prefix: ci
    package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - commit-message:
      include: scope
      prefix: chore
    package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - commit-message:
      prefix: chore
    package-ecosystem: nix
    directory: /
    schedule:
      interval: daily
version: 2
