use camino::Utf8Path;

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    let util_crate_dir = Utf8Path::new(env!("CARGO_MANIFEST_DIR"));
    let store_crate_dir = util_crate_dir.parent().unwrap().join("pr-tracker-store");
    assert!(
        store_crate_dir.exists(),
        "expected {store_crate_dir} to exist",
    );
    println!("cargo:rustc-env=STORE_CRATE_PATH={store_crate_dir}");
}
