use std::path::Path;

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    let util_crate_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let store_crate_dir = util_crate_dir.parent().unwrap().join("store");
    let store_crate_dir_str = store_crate_dir.to_str().unwrap();
    assert!(
        store_crate_dir.exists(),
        "expected {store_crate_dir_str} to exist",
    );
    println!("cargo:rustc-env=STORE_CRATE_PATH={store_crate_dir_str}");
}
