on:
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: NixOS/nix-installer-action@main
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: a-single-key
      - run: nix flake check --accept-flake-config --print-build-logs
